//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymphonyOrchestra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymphonyOrchestra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] instrument {
            get {
                object obj = ResourceManager.GetObject("instrument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Instrument xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Фортепиано&lt;/Name&gt;
        ///  &lt;Type&gt;Клавишный&lt;/Type&gt;
        ///  &lt;Family&gt;Струнные&lt;/Family&gt;
        ///  &lt;Material&gt;Дерево, металл&lt;/Material&gt;
        ///  &lt;Keys&gt;88&lt;/Keys&gt;
        ///&lt;/Instrument&gt;.
        /// </summary>
        internal static string instrument1 {
            get {
                return ResourceManager.GetString("instrument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] musician {
            get {
                object obj = ResourceManager.GetObject("musician", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Musician xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Анна&lt;/Name&gt;
        ///  &lt;Surname&gt;Смирнова&lt;/Surname&gt;
        ///  &lt;Instrument&gt;
        ///    &lt;Name&gt;Скрипка&lt;/Name&gt;
        ///    &lt;Type&gt;Смычковый&lt;/Type&gt;
        ///    &lt;Family&gt;Струнные&lt;/Family&gt;
        ///    &lt;Material&gt;Дерево&lt;/Material&gt;
        ///    &lt;Keys&gt;4&lt;/Keys&gt;
        ///  &lt;/Instrument&gt;
        ///  &lt;Experience&gt;10&lt;/Experience&gt;
        ///  &lt;Section&gt;Первые скрипки&lt;/Section&gt;
        ///&lt;/Musician&gt;.
        /// </summary>
        internal static string musician1 {
            get {
                return ResourceManager.GetString("musician1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] symphony {
            get {
                object obj = ResourceManager.GetObject("symphony", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Symphony xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Title&gt;Симфония №5&lt;/Title&gt;
        ///  &lt;Composer&gt;Людвиг ван Бетховен&lt;/Composer&gt;
        ///  &lt;Duration&gt;35 минут&lt;/Duration&gt;
        ///  &lt;Movements&gt;
        ///    &lt;string&gt;Аллегро&lt;/string&gt;
        ///    &lt;string&gt;Адажио&lt;/string&gt;
        ///    &lt;string&gt;Скерцо&lt;/string&gt;
        ///    &lt;string&gt;Аллегро&lt;/string&gt;
        ///  &lt;/Movements&gt;
        ///  &lt;Year&gt;1804&lt;/Year&gt;
        ///&lt;/Symphony&gt;.
        /// </summary>
        internal static string symphony1 {
            get {
                return ResourceManager.GetString("symphony1", resourceCulture);
            }
        }
    }
}
